language: python
stages:
  - Tests
  - Coverage
  - Github
  - Deploy
services:
  - docker
jobs:
  fast_finish: true
  include:
    - stage: Tests
      script: ./tools/ci/tests.sh
      python:
        - 2.7
        - 3.4
        - 3.5
        - 3.6
        - 3.7
        - 3.8

    - stage: Coverage
      script: ./tools/ci/coverage.sh

    - stage: Github
      script: ./tools/ci/github.sh

    - stage: Deploy
      deploy:
        provider: pypi
        username: ${PYPI_USER}
        password: ${PYPI_PASSWORD}
        on:
          branch: master
