language: python
jobs:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
services:
  - docker
before_install:
  - ./tools/ci/before-install.sh
install:
  - ./tools/ci/install.sh
script:
  - ./tools/ci/run-test.sh
  - ./tools/ci/run-coverage.sh
after_success:
  - ./tools/ci/bump-version.sh
deploy:
  provider: pypi
  username: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    branch: master
