language: python
stages:
  - Tests
  - Coverage
  - Github
  - Deploy

services:
  - docker
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
jobs:
  fast_finish: true
  include:
    - stage: test
      script: ./tools/ci/tests.sh

    - stage: Coverage
      script: ./tools/ci/coverage.sh

    - stage: Github
      script: ./tools/ci/github.sh

    - stage: Deploy
      script: echo "Starting Pypi deploy"
      deploy:
        provider: pypi
        username: ${PYPI_USER}
        password: ${PYPI_PASSWORD}
        on:
          branch: master
