language: python
stages:
  - Tests
  - Coverage
  - Github
  - Deploy
services:
  - docker

before_install: skip
install: skip

jobs:
  fast_finish: true
  include:
    - stage: Tests
      script: ./tools/ci/tests.sh
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

    - stage: Coverage
      script: ./tools/ci/coverage.sh

    - stage: Github
      script: ./tools/ci/github.sh

    - stage: Deploy
      script: echo "Starting Pypi deploy"
      deploy:
        provider: pypi
        username: ${PYPI_USER}
        password: ${PYPI_PASSWORD}
        on:
          branch: master
